#!/bin/bash
cd ~/komodo
if [[ -z $1 ]]; then
  echo "assets-cli commands"
  exit
fi

ac_json=$(curl https://raw.githubusercontent.com/blackjok3rtt/StakedNotary/master/assetchains.json 2>/dev/null)
for row in $(echo "${ac_json}" | jq -c -r '.[]'); do
	_jq() {
     		echo ${row} | jq -r ${1}
    	}
	chain=$(_jq '.ac_name')
  echo $chain
  komodo-cli -ac_name=$chain ${@}
done
